import { Inter } from "next/font/google";
import "./global.css"
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Mostrans Test",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                {children}
                <div className="fixed bottom-0 left-0 right-0">
                    <Footer />
                </div>
            </body>
        </html>
    );
}
